### ISSUE TITLE
Persistent identifiers for use cases

### ISSUE THREAD

**Issue by proycon** [CLARIAH/usecases#11]
At our meeting, the need was expressed to have some kind of persistent identifier for use cases, so we can easily refer to them in discussions.

In order to keep things as simple as possible, we can just give each use case a number, start the filename for that usecase with that number followed by a period. 

Optionally we can add symbolic links to each use case, consisting of only the number (I'll have to confirm first if github redirects properly in such cases).

**Comment by rlzijdeman** [comment]
could we make an issue for each use case? and than tag it with labels?
@rsiebes also argued for a google sheet with (if I recall correctly) rows for the use cases and columns for the tags or claas components

**Comment by proycon** [comment]
Perhaps opening a single dedicated discussion/analysis thread per use case (and labelling it based on things that arise) is indeed a good idea and hopefully invites people to collaborate. In that case I think all such issues should start with a common prefix "[Discussion]". 

Alternatively, GitHub itself has a proper discussion feature now separate from the issue tracker, but I fear that that'll be too confusing for users. I'm also not a fan of creating another external google sheet, that'll lead to more fragmentation. It's hard enough as it is to get people to participate in a single place.

**Comment by rlzijdeman** [comment]
Sounds great, so for usecase https://github.com/CLARIAH/usecases/blob/master/cases/civil-records-linkage.md I would create an issue called "discussion-civil-records-linkage"?

**Comment by proycon** [comment]
I'd say rather with the full title, otherwise it may be too cryptic. Preferably with an extra link to the use case in the issue text for easy access.

**Comment by rlzijdeman** [comment]
done.

**Comment by proycon** [comment]
Technically this issue was about assigning persistent identifiers to each use case (which isn't done), but we sidetracked at went on another path :)

**Comment by proycon** [comment]
But now we indeed have issue numbers for discussion about each use case, and that's probably good enough.
